name: C/C++ CI

on: [push]

jobs:
  build:
    name: Ubuntu-20.04 Focal
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        sudo apt update;
        sudo apt -y install libsleef-dev;
        sudo apt -y install libeigen3-dev;
        sudo apt -y install libopenblas-dev;
        sudo apt -y install libxml2-dev;
        sudo apt -y install libhdf5-dev;
        sudo apt -y install ocaml-nox;
        sudo apt -y install libjgraphx-java;
        sudo apt -y install libflexdock-java;
        sudo apt -y install libjgoodies-looks-java;
        sudo apt -y install libskinlf-java;
        sudo apt -y install libjogl2-java;
    - uses: actions/checkout@v2
    - name: configure
      run: |
        cd scilab
        ./configure --enable-build-parser --without-gui
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
