name: C/C++ CI

on: [push]

jobs:
  build:
    name: Ubuntu-20.04 Focal
    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
